// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: pkg/pb/clothes.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListClotheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Brand    string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	PriceMax int64    `protobuf:"varint,3,opt,name=price_max,json=priceMax,proto3" json:"price_max,omitempty"`
	PriceMin int64    `protobuf:"varint,4,opt,name=price_min,json=priceMin,proto3" json:"price_min,omitempty"`
	Sizes    []string `protobuf:"bytes,5,rep,name=sizes,proto3" json:"sizes,omitempty"`
	Color    string   `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Type     string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Sex      string   `protobuf:"bytes,8,opt,name=sex,proto3" json:"sex,omitempty"`
	Filter   *Filter  `protobuf:"bytes,9,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ListClotheRequest) Reset() {
	*x = ListClotheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_clothes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClotheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClotheRequest) ProtoMessage() {}

func (x *ListClotheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_clothes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClotheRequest.ProtoReflect.Descriptor instead.
func (*ListClotheRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_clothes_proto_rawDescGZIP(), []int{0}
}

func (x *ListClotheRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListClotheRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ListClotheRequest) GetPriceMax() int64 {
	if x != nil {
		return x.PriceMax
	}
	return 0
}

func (x *ListClotheRequest) GetPriceMin() int64 {
	if x != nil {
		return x.PriceMin
	}
	return 0
}

func (x *ListClotheRequest) GetSizes() []string {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *ListClotheRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ListClotheRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListClotheRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *ListClotheRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page         int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize     int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort         string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	SortSafeList []string `protobuf:"bytes,4,rep,name=sort_safe_list,json=sortSafeList,proto3" json:"sort_safe_list,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_clothes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_clothes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_pkg_pb_clothes_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Filter) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Filter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *Filter) GetSortSafeList() []string {
	if x != nil {
		return x.SortSafeList
	}
	return nil
}

type Clothe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price    int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Brand    string   `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Color    string   `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Sizes    []string `protobuf:"bytes,5,rep,name=sizes,proto3" json:"sizes,omitempty"`
	Sex      string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Type     string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	ImageUrl string   `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *Clothe) Reset() {
	*x = Clothe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_clothes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clothe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clothe) ProtoMessage() {}

func (x *Clothe) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_clothes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clothe.ProtoReflect.Descriptor instead.
func (*Clothe) Descriptor() ([]byte, []int) {
	return file_pkg_pb_clothes_proto_rawDescGZIP(), []int{2}
}

func (x *Clothe) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Clothe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Clothe) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Clothe) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Clothe) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Clothe) GetSizes() []string {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *Clothe) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Clothe) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Clothe) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type ClotheList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClotheList []*Clothe `protobuf:"bytes,1,rep,name=clothe_list,json=clotheList,proto3" json:"clothe_list,omitempty"`
}

func (x *ClotheList) Reset() {
	*x = ClotheList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_clothes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClotheList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClotheList) ProtoMessage() {}

func (x *ClotheList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_clothes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClotheList.ProtoReflect.Descriptor instead.
func (*ClotheList) Descriptor() ([]byte, []int) {
	return file_pkg_pb_clothes_proto_rawDescGZIP(), []int{3}
}

func (x *ClotheList) GetClotheList() []*Clothe {
	if x != nil {
		return x.ClotheList
	}
	return nil
}

type ShowClotheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ShowClotheRequest) Reset() {
	*x = ShowClotheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_clothes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowClotheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowClotheRequest) ProtoMessage() {}

func (x *ShowClotheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_clothes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowClotheRequest.ProtoReflect.Descriptor instead.
func (*ShowClotheRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_clothes_proto_rawDescGZIP(), []int{4}
}

func (x *ShowClotheRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateClotheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Clothe *Clothe `protobuf:"bytes,2,opt,name=clothe,proto3" json:"clothe,omitempty"`
}

func (x *UpdateClotheRequest) Reset() {
	*x = UpdateClotheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_clothes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateClotheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClotheRequest) ProtoMessage() {}

func (x *UpdateClotheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_clothes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClotheRequest.ProtoReflect.Descriptor instead.
func (*UpdateClotheRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_clothes_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateClotheRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateClotheRequest) GetClothe() *Clothe {
	if x != nil {
		return x.Clothe
	}
	return nil
}

type DeleteClotheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteClotheRequest) Reset() {
	*x = DeleteClotheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_clothes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClotheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClotheRequest) ProtoMessage() {}

func (x *DeleteClotheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_clothes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClotheRequest.ProtoReflect.Descriptor instead.
func (*DeleteClotheRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_clothes_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteClotheRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteClotheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteClotheResponse) Reset() {
	*x = DeleteClotheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_clothes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClotheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClotheResponse) ProtoMessage() {}

func (x *DeleteClotheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_clothes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClotheResponse.ProtoReflect.Descriptor instead.
func (*DeleteClotheResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_clothes_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteClotheResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pkg_pb_clothes_proto protoreflect.FileDescriptor

var file_pkg_pb_clothes_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0xef, 0x01, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x72, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x4d, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x73,
	0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x24, 0x0a,
	0x0e, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x73, 0x61, 0x66, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x6f, 0x72, 0x74, 0x53, 0x61, 0x66, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0xc7, 0x01, 0x0a, 0x06, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x3b, 0x0a,
	0x0a, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x0b, 0x63,
	0x6c, 0x6f, 0x74, 0x68, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x52, 0x0a,
	0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x11, 0x53, 0x68,
	0x6f, 0x77, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x4b, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6c,
	0x6f, 0x74, 0x68, 0x65, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x22, 0x25, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f,
	0x74, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xa6, 0x02,
	0x0a, 0x0e, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x2c, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65,
	0x12, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x1a, 0x0c,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x22, 0x00, 0x12, 0x35,
	0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x77, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x12, 0x17, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6c, 0x6f,
	0x74, 0x68, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f,
	0x74, 0x68, 0x65, 0x12, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6c, 0x6f, 0x74, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00,
	0x12, 0x39, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65,
	0x12, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c,
	0x6f, 0x74, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x6c,
	0x6f, 0x74, 0x68, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_clothes_proto_rawDescOnce sync.Once
	file_pkg_pb_clothes_proto_rawDescData = file_pkg_pb_clothes_proto_rawDesc
)

func file_pkg_pb_clothes_proto_rawDescGZIP() []byte {
	file_pkg_pb_clothes_proto_rawDescOnce.Do(func() {
		file_pkg_pb_clothes_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_clothes_proto_rawDescData)
	})
	return file_pkg_pb_clothes_proto_rawDescData
}

var file_pkg_pb_clothes_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_pb_clothes_proto_goTypes = []interface{}{
	(*ListClotheRequest)(nil),    // 0: auth.ListClotheRequest
	(*Filter)(nil),               // 1: auth.Filter
	(*Clothe)(nil),               // 2: auth.Clothe
	(*ClotheList)(nil),           // 3: auth.ClotheList
	(*ShowClotheRequest)(nil),    // 4: auth.ShowClotheRequest
	(*UpdateClotheRequest)(nil),  // 5: auth.UpdateClotheRequest
	(*DeleteClotheRequest)(nil),  // 6: auth.DeleteClotheRequest
	(*DeleteClotheResponse)(nil), // 7: auth.DeleteClotheResponse
}
var file_pkg_pb_clothes_proto_depIdxs = []int32{
	1, // 0: auth.ListClotheRequest.filter:type_name -> auth.Filter
	2, // 1: auth.ClotheList.clothe_list:type_name -> auth.Clothe
	2, // 2: auth.UpdateClotheRequest.clothe:type_name -> auth.Clothe
	2, // 3: auth.ClothesService.CreateClothe:input_type -> auth.Clothe
	4, // 4: auth.ClothesService.ShowClothe:input_type -> auth.ShowClotheRequest
	0, // 5: auth.ClothesService.ListClothe:input_type -> auth.ListClotheRequest
	5, // 6: auth.ClothesService.UpdateClothe:input_type -> auth.UpdateClotheRequest
	6, // 7: auth.ClothesService.DeleteClothe:input_type -> auth.DeleteClotheRequest
	2, // 8: auth.ClothesService.CreateClothe:output_type -> auth.Clothe
	2, // 9: auth.ClothesService.ShowClothe:output_type -> auth.Clothe
	3, // 10: auth.ClothesService.ListClothe:output_type -> auth.ClotheList
	2, // 11: auth.ClothesService.UpdateClothe:output_type -> auth.Clothe
	2, // 12: auth.ClothesService.DeleteClothe:output_type -> auth.Clothe
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_pb_clothes_proto_init() }
func file_pkg_pb_clothes_proto_init() {
	if File_pkg_pb_clothes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_clothes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClotheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_clothes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_clothes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Clothe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_clothes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClotheList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_clothes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowClotheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_clothes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateClotheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_clothes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClotheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_clothes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClotheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_clothes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_clothes_proto_goTypes,
		DependencyIndexes: file_pkg_pb_clothes_proto_depIdxs,
		MessageInfos:      file_pkg_pb_clothes_proto_msgTypes,
	}.Build()
	File_pkg_pb_clothes_proto = out.File
	file_pkg_pb_clothes_proto_rawDesc = nil
	file_pkg_pb_clothes_proto_goTypes = nil
	file_pkg_pb_clothes_proto_depIdxs = nil
}
